# Generated by Django 4.2 on 2023-04-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=60, verbose_name='Датчик')),
                ('description', models.CharField(default=None, max_length=60, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Показания температуры датчика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время передачи показаний датчика')),
                ('image', models.ImageField(max_length=60, null=True, upload_to='', verbose_name='Фото объекта')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor')),
            ],
        ),
    ]
